server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/game?characterEncoding=utf8&serverTimezone=GMT&useSSL=false&useAffectedRows=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: '!Wstly1221'
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
      lettuce:
        shutdown-timeout: 10000
      password: '!Wstly1221'
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.s1mpie.gameserver.model