server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/game?characterEncoding=utf8&serverTimezone=GMT&useSSL=false&useAffectedRows=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: '!Wstly1221'
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.s1mpie.gameserver.model